// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdnpeYWk3fC_R27CGEENEq-up0m9Yxw5o',
    appId: '1:739346128775:web:4a55a99ee8710e9cbb3d22',
    messagingSenderId: '739346128775',
    projectId: 'final-project-8a165',
    authDomain: 'final-project-8a165.firebaseapp.com',
    storageBucket: 'final-project-8a165.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMcO9crMGXqzw0zg4NADdFp8rp7-vP1M',
    appId: '1:739346128775:android:891431f731ea4511bb3d22',
    messagingSenderId: '739346128775',
    projectId: 'final-project-8a165',
    storageBucket: 'final-project-8a165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEiqiYa8HI7hSKEXi9jeLfvmD_P2v59A',
    appId: '1:739346128775:ios:16c3992a827602dcbb3d22',
    messagingSenderId: '739346128775',
    projectId: 'final-project-8a165',
    storageBucket: 'final-project-8a165.firebasestorage.app',
    androidClientId: '739346128775-ntubhehum4sni46ga0tvp8c9r9r4sv51.apps.googleusercontent.com',
    iosClientId: '739346128775-3o2bcs1lcutc0d82dlfle6shc0kb9dsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cineverseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEiqiYa8HI7hSKEXi9jeLfvmD_P2v59A',
    appId: '1:739346128775:ios:16c3992a827602dcbb3d22',
    messagingSenderId: '739346128775',
    projectId: 'final-project-8a165',
    storageBucket: 'final-project-8a165.firebasestorage.app',
    androidClientId: '739346128775-ntubhehum4sni46ga0tvp8c9r9r4sv51.apps.googleusercontent.com',
    iosClientId: '739346128775-3o2bcs1lcutc0d82dlfle6shc0kb9dsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cineverseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdnpeYWk3fC_R27CGEENEq-up0m9Yxw5o',
    appId: '1:739346128775:web:0d4661449fd43ababb3d22',
    messagingSenderId: '739346128775',
    projectId: 'final-project-8a165',
    authDomain: 'final-project-8a165.firebaseapp.com',
    storageBucket: 'final-project-8a165.firebasestorage.app',
  );

}